# NumPy 

To get started we need to install it!

In [2]:
#!pip install numpy

## Importing NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

# NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

In [6]:
my_list = [1, 2, 3, 4]
#print(my_list)
my_list

[1, 2, 3, 4]

In [7]:
type(my_list)

list

## Creating NumPy Arrays from Objects

### From a Python List

We can create an array by directly converting a list or list of lists:

In [12]:
a = [1, 2, 3]
print(a)

[1, 2, 3]


In [13]:
my_array = np.array(a)
my_array

array([1, 2, 3])

In [10]:
print(np.array(a))

[1 2 3]


In [14]:
type(my_array)

numpy.ndarray

In [15]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
len(my_matrix)

3

In [16]:
type(my_matrix)

list

In [19]:
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Built-in Methods to create arrays

There are lots of built-in ways to generate arrays.

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [22]:
print(*range(10)) #stop

0 1 2 3 4 5 6 7 8 9


In [23]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [24]:
print(list(range(5, 10)))

[5, 6, 7, 8, 9]


In [25]:
print(list(range(5, 100, 5)))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [29]:
print(np.arange(2, 10))

[2 3 4 5 6 7 8 9]


In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.zeros((5,4), dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
np.zeros((5,4), "str")

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [50]:
np.zeros((2,2), bool)

array([[False, False],
       [False, False]])

In [39]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
np.ones((3,2), "str")

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [51]:
np.ones((2,2), bool)

array([[ True,  True],
       [ True,  True]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [42]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [43]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.eye(9, k=3)

array([[0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
np.eye(9, k=3, dtype="int")

array([[0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [53]:
np.random.rand(5)

array([0.72629642, 0.65142718, 0.72036364, 0.26627202, 0.80656146])

In [59]:
np.random.rand(5,2)

array([[0.00874101, 0.99749769],
       [0.85787819, 0.8796761 ],
       [0.59370964, 0.72888027],
       [0.40705763, 0.36782906],
       [0.36468662, 0.26343134]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [61]:
np.random.randn(2)

array([ 0.12563256, -0.20930677])

In [62]:
np.random.randn(2,3)

array([[-1.15017651, -0.08071714, -0.41308141],
       [-1.81265847, -0.90357329, -0.20078535]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [68]:
np.random.randint(5)

2

In [69]:
np.random.randint(1,100)

84

In [70]:
np.random.randint(1,100, 5)

array([70, 59, 32, 13, 90])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [71]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [72]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [85]:
arr = np.arange(0,25)
ranarr = np.random.randint(0, 50,10)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [77]:
np.reshape(arr, (5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
arr #arr'da kalıcı bir değişiklik olmadı.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [93]:
arr = arr.reshape(5,5)

In [94]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
arr.reshape(-1) #Çok boyutlu bir array i 1 boyuta döndürür

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [98]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [99]:
arr.shape

(5, 5)

In [100]:
arr.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [101]:
arr.reshape(25).shape

(25,)

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [102]:
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [103]:
ranarr.shape

(10,)

In [104]:
ranarr.max()

43

In [105]:
ranarr.min()

1

In [106]:
ranarr.argmax()

3

In [109]:
ranarr.argmin()

1

In [111]:
arr.max()

24

In [115]:
arr.min()

0

In [114]:
arr.argmax()

24

In [116]:
arr.argmin()

0

## Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [117]:
arr.shape

(5, 5)

In [126]:
arr = arr.reshape(-1) #1 boyutlu array
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [120]:
arr.shape

(25,)

In [121]:
arr.reshape(1,25) #1'e 25'lik 2 boyutlu array 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [125]:
print(arr.reshape(1,25))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]


In [122]:
arr.reshape(1,25).shape

(1, 25)

In [123]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [128]:
arr.reshape(25,1).arr.

(25, 1)

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [130]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [129]:
arr.dtype

dtype('int32')

In [131]:
arr2 = np.array([1.5, 8.9])
arr2.dtype

dtype('float64')

In [132]:
arr3 = np.array([1.5, 8.9, 10])
arr3.dtype

dtype('float64')

In [133]:
arr4 = np.array([50, 8.9, 10])
arr4.dtype

dtype('float64')

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [134]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [135]:
arr[6] #index 

6

In [136]:
arr[0:6] #slicing

array([0, 1, 2, 3, 4, 5])

In [138]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [139]:
arr[6:11]

array([ 6,  7,  8,  9, 10])

In [140]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [141]:
arr[3:7]

array([3, 4, 5, 6])

## Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [142]:
liste = [1,2,3,4]

In [144]:
liste[3] = 9

In [145]:
liste

[1, 2, 3, 9]

In [147]:
liste[0:2] = [5,6]

In [148]:
liste

[5, 6, 3, 9]

In [149]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [152]:
arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [154]:
arr = 99
arr

99

In [155]:
type(arr)

int

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [156]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [157]:
arr_2d.shape

(3, 3)

In [158]:
arr_2d[1]

array([20, 25, 30])

In [161]:
arr_2d[2]

array([35, 40, 45])

In [162]:
arr_2d[1][2]

30

In [163]:
arr_2d[1, 2]

30

In [164]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [165]:
arr_2d[0:2, 1:]

array([[10, 15],
       [25, 30]])

In [167]:
arr_2d[2, :2]

array([35, 40])

In [168]:
arr_2d[2, 2]

45

## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:

<img src= 'numpy_indexing.png' width=500/> Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [169]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [171]:
bool_arr = arr > 4

In [172]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [173]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [174]:
arr[arr < 2]

array([1])

In [177]:
arr == 5

array([False, False, False, False,  True, False, False, False, False,
       False])

In [176]:
arr[arr == 5]

array([5])

In [179]:
arr != 5

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [178]:
arr[arr != 5]

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform *array with array* arithmetic, or *scalar with array* arithmetic. Let's see some examples:

In [180]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [181]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [183]:
my_list + my_list

[1, 2, 3, 4, 1, 2, 3, 4]

In [185]:
liste = []
for i in my_list:
    i += i
    liste.append(i)
print(liste)

[2, 4, 6, 8]


In [186]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [188]:
# my_list * my_list

In [189]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [190]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [192]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
x = arr2 / arr2
x

C:\Users\oznur\AppData\Local\Temp\ipykernel_7768\1956273973.py:1: RuntimeWarning: invalid value encountered in true_divide
  x = arr2 / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [196]:
1/ arr

C:\Users\oznur\AppData\Local\Temp\ipykernel_7768\3009366600.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [198]:
arr + 5 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [199]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [201]:
arr_2d + arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [204]:
arr_x = np.array(([2], [2]))
arr_x.shape

(2, 1)

In [207]:
# arr_2d * arr_x #hata alırız çünkü aynı boyutta değiller

## Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [209]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [210]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [211]:
np.log(arr)

C:\Users\oznur\AppData\Local\Temp\ipykernel_7768\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [212]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [241]:
np.std(arr)

3.197221015541813

## Summary Statistics on Arrays

NumPy also offers common summary statistics like <em>sum</em>, <em>mean</em> and <em>max</em>. You would call these as methods on an array.

In [215]:
len(arr)

10

In [213]:
arr.sum()

45

In [214]:
arr.mean()

4.5

In [217]:
arr.min()

0

In [219]:
arr.shape

(10,)

## Axis Logic
When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

Let's see how this affects our summary statistic calculations from above.

In [223]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [221]:
arr_2d.sum() #axis=none

225

In [222]:
arr_2d.sum(axis=1)

array([ 30,  75, 120])

In [224]:
arr_2d.sum(axis=0)

array([60, 75, 90])

In [225]:
arr_2d.mean(axis=1)

array([10., 25., 40.])

### Array lerde Arama İşlemleri
- where

In [226]:
arr = np.array([1, 5, 8, 6, 4, 8 ,9 , 1, 0])
arr

array([1, 5, 8, 6, 4, 8, 9, 1, 0])

In [228]:
np.where(arr%2==0) #koşulu sağlayan değerlerin index numaraları döndürür

(array([2, 3, 4, 5, 8], dtype=int64),)


In [229]:
np.where(arr%2==1) 

(array([0, 1, 6, 7], dtype=int64),)

In [230]:
arr[np.where(arr%2==1)]

array([1, 5, 9, 1])

In [231]:
arr[arr%2==1]

array([1, 5, 9, 1])

- sort

In [232]:
arr

array([1, 5, 8, 6, 4, 8, 9, 1, 0])

In [233]:
np.sort(arr)

array([0, 1, 1, 4, 5, 6, 8, 8, 9])

In [236]:
arr2 = np.array([[1,2], [9, 3], [5,4]])
arr2

array([[1, 2],
       [9, 3],
       [5, 4]])

In [240]:
np.sort(arr2)

array([[1, 2],
       [3, 9],
       [4, 5]])

In [238]:
np.sort(arr2, axis=0)

array([[1, 2],
       [5, 3],
       [9, 4]])

In [239]:
np.sort(arr2, axis=1)

array([[1, 2],
       [3, 9],
       [4, 5]])